name: Test
on:
  pull_request:
    types:
      - "ready_for_review"
    branches:
      - "main"
jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: ChatGPT Review
        uses: ShintaroaSuzuki/chatgpt-review@main
        with:
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}
