name: "ChatGPT Review"
author: "ShintaroaSuzuki"
description: ""
inputs:
  openai_api_key:
    description: "OPENAI API KEY"
    required: true
  review_ignore_path:
    description: "REVIEW IGNORE PATH"
    required: false
runs:
  using: "docker"
  image: "Dockerfile"
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
branding:
  icon: "message-circle"
  color: "gray-dark"
