name: "ChatGPT Review"
author: "ShintaroaSuzuki"
description: ""
inputs:
  github_token:
    description: "GITHUB TOKEN"
    required: true
  openai_api_key:
    description: "OPENAI API KEY"
    required: true
  review_ignore_path:
    description: "REVIEW IGNORE PATH"
    required: false
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icon: "message-circle"
  color: "gray-dark"
